import { createApp } from "vue";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import App from "./App.vue";
import router from "./router";
import { createPinia } from "pinia";
import { useAuthStore } from "./stores/auth";
import "./styles/global.css";
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
useAuthStore(pinia).restore();
app.use(router);
app.use(ElementPlus);
app.mount("#app");
